[workspace]
members = [
    "core",
    "core/macros",
    "dom",
    "features",
    "html",
    "html/macros",
    "i18n",
    "log",
    "macro-tools",
    "node",
    "nw",
    "panic-hook",
    "rpc",
    "rpc/macros",
    "store",
    "task",
    "task/macros",
    "terminal",
    "wasm",
    "wasm/macros",
    "websocket",
    "examples/rpc/client-browser/wasm",
    "examples/rpc/client-native",
    "examples/rpc/client-common",
    "examples/rpc/messages",
    "examples/rpc/server",
    "examples/websocket/client-browser/wasm",
    "examples/websocket/client-common",
    "examples/websocket/client-native",
    "examples/websocket/server",
    "examples/terminal/cli",
    "examples/terminal/native",
    "examples/terminal/wasm",
]

[workspace.package]
version = "0.3.17"
authors = ["Anton Yemelyanov <anton.yemelyanov@gmail.com>", "Surinder Singh Matoo Mattaur <surinder83singh@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
include = ["src/**/*.rs", "Cargo.toml"]
repository = "https://github.com/workflow-rs/workflow-rs"

[workspace.dependencies]

# internal dependencies

workflow-core = { version = "0.3.17", path = "core" }
workflow-core-macros = { version = "0.3.17", path = "core/macros" }
workflow-dom = { version = "0.3.17", path = "dom" }
workflow-html = { version = "0.3.17", path = "html" }
workflow-html-macros = { version = "0.3.17", path = "html/macros" }
workflow-i18n = { version = "0.3.17", path = "i18n" }
workflow-log = { version = "0.3.17", path = "log" }
workflow-macro-tools = { version = "0.3.17", path = "macro-tools" }
workflow-node = { version = "0.3.17", path = "node" }
workflow-nw = { version = "0.3.17", path = "nw" }
workflow-panic-hook = { version = "0.3.17", path = "panic-hook" }
workflow-rpc = { version = "0.3.17", path = "rpc" }
workflow-rpc-macros = { version = "0.3.17", path = "rpc/macros" }
workflow-rs = { version = "0.3.17", path = "features" }
workflow-store = { version = "0.3.17", path = "store" }
workflow-task = { version = "0.3.17", path = "task" }
workflow-task-macros = { version = "0.3.17", path = "task/macros" }
workflow-terminal = { version = "0.3.17", path = "terminal" }
workflow-wasm = { version = "0.3.17", path = "wasm" }
workflow-wasm-macros = { version = "0.3.17", path = "wasm/macros" }
workflow-websocket = { version = "0.3.17", path = "websocket" }

# external dependencies

ahash = "0.8.3"
async-channel = "1.8.0"
async-std = { version = "1.12.0", features = ['attributes'] }
async-trait = "0.1.64"
base64 = "0.21.0"
# borsh = { version = "0.10.0", features = ["rc"] }
borsh = { version = "0.9.1", features = ["rc"] }
bs58 = "0.4.0"
cfg-if = "1.0.0"
console = "0.15.5"
convert_case = "0.6.0"
crossterm = "0.26.0"
clap = { version = "4.1.4", features = ["derive","cargo"] }
downcast = "0.11.0"
downcast-rs = "1.2.0"
faster-hex = "0.6.1"
futures = "0.3.26"
futures-util = { version = "0.3.26", default-features = false, features = ["sink", "std"] }
getrandom = {version = "0.2.8", features=["js"]}
hexplay = "0.2.1"
home = "0.5.4"
instant = { version ="0.1.12", features = ['wasm-bindgen'] }
js-sys = "0.3.61"
lazy_static = "1.4.0"
log = "0.4.17"
manual_future = "0.1.1"
node-child-process = "0.1.1"
node-sys = "0.4.2"
numtoa = "0.2.4"
nw-sys="0.1.2"
parse-variants = "0.1.1"
proc-macro-error = { version = "1.0.4", default-features = false }
proc-macro2 = { version = "1.0.50" }
quote = "1.0.23"
rand = { version = "0.8.5", features = ["getrandom"] }
regex = "1.7.1"
ritehash = "0.2.0"
serde = { version = "1.0.152" , features = ["derive","rc"] }
serde_json = "1.0.91"
serde-wasm-bindgen = "0.4.5"
sha2 = "0.10.6"
syn = {version="1.0.107",features=["full","fold","extra-traits","parsing","proc-macro"]}
termcolor="0.3.6"
termion = "2.0.1"
# termion = "1.5.6"
thiserror = "1.0.38"
tokio = { version = "1.25.0", default-features = false, features = ['io-util','time','sync','macros','rt','rt-multi-thread'] }
tokio-tungstenite = { version = "0.18.0", features = ["handshake"] }
triggered = "0.1.2"
tungstenite = { version = "0.18.0", features = ["handshake"] }
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
web-sys = "0.3.61"
workflow-async-trait = "0.1.68"
