[workspace]
members = [
    "macro-tools",
    "log",
    "core",
    "wasm",
    "panic-hook",
    "node",
    "nw",
    "websocket",
    "rpc",
    "dom",
    "html",
    "i18n",
    "terminal",
]

[workspace.package]
version = "0.3.0"
authors = ["https://aspectron.tech"]
license = "MIT or Apache-2.0"
edition = "2021"
include = ["src/**/*.rs", "Cargo.toml"]

[workspace.dependencies]
workflow-macro-tools = { path = "macro-tools" }
workflow-log = { path = "log" }
workflow-core = { path = "core" }
workflow-wasm = { path = "wasm" }
workflow-panic-hook = { path = "panic-hook" }
workflow-node = { path = "node" }
workflow-nw = { path = "nw" }
workflow-websocket = { path = "websocket" }
workflow-rpc = { path = "rpc" }
workflow-dom = { path = "dom" }
workflow-html = { path = "html" }
workflow-i18n = { path = "i18n" }
workflow-terminal = { path = "terminal" }


nw-sys={path="../nw-sys"}

# workflow-unistore = { path = "../workflow-unistore", optional = true }

