[package]
name = "workflow-rpc"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-rpc"
keywords = ["websocket","rpc","wasm","browser"]
categories = ["web-programming::websocket","web-programming::http-client"]
exclude = ["/.*", "/test"]
description = """
RPC layer based on workflow-websocket crate offering native & in-browser clients as well as a native-only server
"""

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
workflow-rpc-macros = { path = "macros" }
workflow-log.workspace = true
workflow-core.workspace = true
workflow-websocket.workspace = true
async-trait = "0.1.61"
wasm-bindgen = "0.2.83"
borsh = "0.10.0"
serde = "1.0.152"
serde_json = "1.0.91"
manual_future = "0.1.1"
ahash = "0.8.2"
thiserror = "1.0.38"
rand = { version = "0.8.5", features = ["getrandom"] }
futures = "0.3.25"
async-std = { version = "1.12.0", features = ['attributes'] }
downcast-rs = "1.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ['js'] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
tokio = { version = "1.24.2", default-features = false, features = ['io-util','time','sync','macros','rt'] }
tungstenite = { version = "0.18.0", default-features = false }
