[package]
name = "workflow-store"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-unistore"
keywords = ["wasm","framework","storage","browser","localstorage","file","io"]
categories = []
exclude = ["/.*", "/test"]
description = """
File storage access crate abstracting file I/O and browser localstorage
"""

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base64.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std.workspace = true
home.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    'Window',
    'Storage',
]
