[package]
name = "workflow-panic-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if.workspace = true
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    'console',
    'Window',
    'Document',
    'Element',
    'HtmlElement',
]
