[package]
name = "rpc-example-client-browser"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rpc-example-client-common = { path = "../../client-common" }

workflow-log.workspace = true
workflow-html.workspace = true
workflow-rpc.workspace = true
workflow-wasm.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    'Window',
    'Document',
    'Element',
    'Text',
]
