[package]
name = "workflow-nw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

wasm-bindgen = "0.2.79"
js-sys = "0.3.56"
nw-sys.workspace = true
workflow-log.workspace = true
workflow-wasm.workspace = true
workflow-dom.workspace = true

[dependencies.web-sys]
version = "0.3.60"
features = [
    'console',
    'Document',
    'Window',
    'HtmlElement',
    'HtmlVideoElement',
    'CustomEvent',
    'MouseEvent',
    'Navigator',
    'MediaDevices',
    'MediaStreamConstraints',
    'MediaStream',
    'MediaStreamTrack'
]
