[package]
name = "terminal-example-native"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
terminal-example-cli = { path = "../cli" }
workflow-terminal.workspace = true
workflow-log.workspace = true
async-std.workspace = true
async-trait.workspace = true
cfg-if.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true
