[package]
name = "workflow-dom"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-dom"
keywords = ["wasm","dom","inject","script","css"]
categories = ["web-programming::http-client","wasm"]
exclude = ["/.*", "/test"]
description = """
DOM injection utilities for run-time injection of JavaScript and CSS
"""

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
futures.workspace = true
js-sys.workspace = true
regex.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-wasm.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    'Window',
    'Document',
    'Element',
    'Url',
    'Blob',
    'CustomEvent',
    'Node',
    'NodeList',
    'HtmlCollection',
    'BlobPropertyBag'
]