[package]
name = "workflow-rpc-macros"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-rpc"
keywords = ["rpc"]
categories = []
exclude = ["/.*", "/test"]
description = """
Macros for the workflow-rpc crate
"""

[lib]
proc-macro = true

[dependencies]
parse-variants.workspace = true
proc-macro-error.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
workflow-macro-tools.workspace = true
