[package]
name = "workflow-rpc-macros"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version= "0.3.2"
keywords = ["rpc"]
categories = []
exclude = ["/.*", "/test"]
description = """
Macros for the workflow-rpc crate
"""

[lib]
proc-macro = true

[dependencies]
parse-variants.workspace = true
proc-macro-error.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
# workflow-macro-tools.workspace = true
