[package]
name = "terminal-example-wasm"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
terminal-example-cli = { path = "../cli" }
workflow-terminal.workspace = true
workflow-log.workspace = true
async-trait.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
console_error_panic_hook = "0.1.7"
