[package]
name = "workflow-websocket"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/workflow-rs/workflow-websocket"
keywords = ["wasm","websocket","browser","rpc"]
categories = ["web-programming::websocket","web-programming::http-client","api-bindings"]
exclude = ["/.*", "/test"]
description = """
WebSocket crate (client and server) with a uniform native and in-browser async Rust API
"""

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
workflow-core.workspace = true
workflow-log.workspace = true
workflow-wasm.workspace = true

cfg-if = "1.0.0"
futures = "0.3.25"
futures-util = { version = "0.3.25", default-features = false, features = ["sink", "std"] }
manual_future = "0.1.1"
async-std = { version = "1.12.0", features = ['attributes'] }
thiserror = "1.0.38"
triggered = "0.1.2"
wasm-bindgen = "0.2.83"
downcast-rs = "1.2.0"
async-trait = "0.1.61"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.24.2", default-features = false, features = ['io-util','time','sync','macros','rt-multi-thread'] }
ahash = "0.8.2"
tokio-tungstenite = "0.18.0"
tungstenite = { version = "0.18.0", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"

[target.'cfg(not(target_os = "solana"))'.dependencies.web-sys]
version = "0.3.60"
features = [
    "console",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "CloseEvent",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
    "DomException",
]
